name: test-lando-named-removal-plugin
recipe: lamp

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@florianPat/lando-plugin-named-volume-removal": ./../../
